name: Deploy api

on:
  workflow_dispatch: {}

env:
  AZURE_FUNCTIONAPP_NAME: 'actions-command-center'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  node-version: 18.x

permissions:
  id-token: write # OIDC
  contents: read  # actions/checkout

jobs:
  deploy:
    name: Deploy api
    concurrency: api-deploy-prod
    runs-on: ubuntu-latest
    environment:
      name: api
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: 8787c6d9-19de-4ab8-9966-36519cf10ffb # actions-command-center-github-actions
          tenant-id: 87e276c0-7d18-4d86-948a-ba5eea990211
          subscription-id: 7100b295-05bb-4ecf-a59b-246bd1f17d9a # Microsoft Credits Subscription
      - name: Cache node modules
        uses: actions/cache@v2.1.8
        with:
          path: ./api/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node ${{ env.node-version }}
        uses: actions/setup-node@v2.5.2
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
        shell: bash
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      - run: npm run build
        shell: bash
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      - name: Deploy Azure Function App
        uses: Azure/functions-action@v1.5.0
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
