name: Deploy all

on:
  workflow_dispatch: {}

permissions:
  id-token: write # OIDC
  contents: write # Needed for committing to github-pages branch

jobs:
  deploy-api:
    name: Deploy api
    uses: ./.github/workflows/api-deploy.yaml
  deploy-web:
    name: Deploy web
    uses: ./.github/workflows/web-deploy.yaml
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
