name: Build and deploy

on:
  push:
    branches: ["main"]
    paths: ["web/**"]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ng deploy
        working-directory: ./web
