name: Deploy all

on:
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  id-token: write # OIDC
  contents: write # Needed for committing to github-pages branch

concurrency:
  group: all
  cancel-in-progress: false

jobs:
  deploy-api:
    uses: ./.github/workflows/api-deploy.yaml
  deploy-web:
    uses: ./.github/workflows/web-deploy.yaml
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
