name: Deploy web app

on:
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  node-version: 18.x

jobs:
  deploy:
    name: Deploy web app
    environment:
      name: web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v2.1.8
        with:
          path: ./web/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node ${{ env.node-version }}
        uses: actions/setup-node@v2.5.2
        with:
          node-version: ${{ env.node-version }}
      - name: Install
        run: npm ci
        working-directory: ./web
      - name: Lint
        run: npm run lint
        working-directory: ./web
      - name: Build
        run: npm run deploy -- --dry-run
        working-directory: ./web
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npm run deploy -- --no-build
        working-directory: ./web
